#!/bin/sh

#
# Initial flashing of u-boot
#

set -o errexit

# machine specific data
uboot_file="owa5x-flash.bin"
uboot_block_size=1024
uboot_seek_blocks=32
uboot_device="/dev/mmtd"

#echo 0 > /sys/block/mmcblk2boot0/force_ro
#dd if=/mnt/boot/$uboot_file of=$uboot_device conv=fdatasync seek=$uboot_seek_blocks bs=$uboot_block_size
#echo 1 > /sys/block/mmcblk2boot0/force_ro
