#@TYPE: Machine
#@NAME: Owasys owa5x
#@SOC: i.MX8 MP
#@DESCRIPTION: Machine configuration for Owasys owa5x
#@MAINTAINER: Alvaro Guzman <alvaro.guzman@owasys.com>

MACHINEOVERRIDES =. "owa5x-nand:"

require conf/machine/owa5x-nand.conf
